LOGGING_CONFIG_FILE_PATH = "static/logging_config.json"
OUTPUT_DIR_NAME = "output"
PIE_CHART_PATH = "output/portfolio_distribution.png"
SCHEMA_FILE_PATH = "static/stocks.xsd"
STOCK_FILE_PATH = "data/stocks.xml"
